name: BBC Football Telegram Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Allows manual run
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.3 feedparser requests beautifulsoup4

      - name: Run Telegram Bot
        run: |
          python bot.py & sleep 120  # let it post the feed once then exit

      - name: Commit and Push posted.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted.json
          git diff --cached --quiet || git commit -m "Update posted.json after running bot"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Harkinmate/Football-news-bot.git HEAD:main
